development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ulgood_production
  pool: 5
  username: root
  password:
  host: localhost

#production:
#  adapter: postgresql
#  encoding: unicode
#  database: untitled1_production
#  pool: 5
#  username: untitled1
#  password: